// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCByyYwkfsgQJFBeiBwAkt_NgQnWYErCCo',
    appId: '1:1002620237242:web:5bf5e203a4c07d95c0d983',
    messagingSenderId: '1002620237242',
    projectId: 'unanimaux',
    authDomain: 'unanimaux.firebaseapp.com',
    storageBucket: 'unanimaux.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDq1Q7aPXxbH14aQ2jMwbCIrenEUI5las',
    appId: '1:1002620237242:android:9aaed11ce765d4a5c0d983',
    messagingSenderId: '1002620237242',
    projectId: 'unanimaux',
    storageBucket: 'unanimaux.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh5Xqmu18gUISXkLjcJyFS94yuOU_wcZs',
    appId: '1:1002620237242:ios:5e67f985bd4c9347c0d983',
    messagingSenderId: '1002620237242',
    projectId: 'unanimaux',
    storageBucket: 'unanimaux.firebasestorage.app',
    iosBundleId: 'fr.unanimaux.unanimaux',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh5Xqmu18gUISXkLjcJyFS94yuOU_wcZs',
    appId: '1:1002620237242:ios:5e21bb4b4e9d5c6bc0d983',
    messagingSenderId: '1002620237242',
    projectId: 'unanimaux',
    storageBucket: 'unanimaux.firebasestorage.app',
    iosBundleId: 'com.example.unanimaux',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCByyYwkfsgQJFBeiBwAkt_NgQnWYErCCo',
    appId: '1:1002620237242:web:ee81701b6e452418c0d983',
    messagingSenderId: '1002620237242',
    projectId: 'unanimaux',
    authDomain: 'unanimaux.firebaseapp.com',
    storageBucket: 'unanimaux.firebasestorage.app',
  );
}
